src/Entity/File/File.php
<?php

/*
 * This file is part of a Lyssal project.
 *
 * @copyright Rémi Leclerc
 */

namespace App\Entity\File;

use App\Entity\Traits\IdTrait;
use Doctrine\ORM\Mapping as ORM;
use Lyssal\EntityBundle\Entity\Traits\UpdatedAtTrait;
use Lyssal\EntityBundle\Traits\UploadedFileTrait;
use Lyssal\File\File as LyssalFile;

/**
 * A file.
 *
 * @category Entity
 *
 * @author    Rémi Leclerc
 * @copyright 2019 Rémi Leclerc
 * @license   MIT https://opensource.org/licenses/MIT
 *
 * @see https://gitlab.com/Lyssal/collectolys
 *
 * @ORM\MappedSuperclass()
 * @ORM\HasLifecycleCallbacks()
 */
abstract class File
{
    use IdTrait;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $filename;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $path;

    use UpdatedAtTrait;

    /**
     * The file to upload.
     *
     * @var \Symfony\Component\HttpFoundation\File\File
     */
    protected $uploadedFile;

    use UploadedFileTrait;

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    /**
     * @see UploadedFileTrait::setUploadedFile()
     */
    public function setUploadedFile($uploadedFile = null)
    {
        $this->uploadedFile = $uploadedFile;
        // Force the event if no other property is modified
        $this->initUpdatedAt();

        return $this;
    }

    /**
     * Get the filename.
     */
    public function __toString(): string
    {
        return (string) $this->filename;
    }

    /**
     * Get the file URL.
     */
    public function getUrl(): string
    {
        return str_replace(\DIRECTORY_SEPARATOR, '/', $this->getPathname());
    }

    /**
     * Get the file path.
     */
    public function getPathname(): string
    {
        return $this->getUploadedFileDirectory().\DIRECTORY_SEPARATOR.$this->filename;
    }

    /**
     * Delete the image.
     *
     * @ORM\PostRemove()
     */
    public function deleteFile(): void
    {
        if (null !== $this->filename) {
            $file = new LyssalFile($this->getPathname());
            $file->delete();
        }
    }
}

src/Entity/Type.php
<?php

/*
 * This file is part of a Lyssal project.
 *
 * @copyright Rémi Leclerc
 */

namespace App\Entity;

use App\Entity\Element\SpecialSet;
use App\Entity\File\IconableInterface;
use App\Entity\Support\Support;
use App\Entity\Traits\IconTrait;
use App\Entity\Traits\IdTrait;
use App\Entity\Traits\PositionTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Lyssal\Color\Color;
use Lyssal\Entity\Model\Breadcrumb\BreadcrumbableInterface;
use Lyssal\EntityBundle\Entity\RoutableInterface;

/**
 * An element type.
 *
 * @category Entity
 *
 * @author    Rémi Leclerc
 * @copyright 2019 Rémi Leclerc
 * @license   MIT https://opensource.org/licenses/MIT
 *
 * @see https://gitlab.com/Lyssal/collectolys
 *
 * @ORM\Entity(repositoryClass="App\Doctrine\Repository\TypeRepository")
 */
class Type implements IconableInterface, RoutableInterface, BreadcrumbableInterface
{
    use IconTrait;
    use IdTrait;
    use PositionTrait;

    /**
     * The audio ID.
     *
     * @var int
     */
    const AUDIO = 1;

    /**
     * The video ID.
     *
     * @var int
     */
    const VIDEO = 2;

    /**
     * The software ID.
     *
     * @var int
     */
    const SOFTWARE = 3;

    /**
     * The video game ID.
     *
     * @var int
     */
    const VIDEO_GAME = 4;

    /**
     * The book ID.
     *
     * @var int
     */
    const BOOK = 5;

    /**
     * The periodical ID.
     *
     * @var int
     */
    const PERIODICAL = 6;

    /**
     * The cooking recipe ID.
     *
     * @var int
     */
    const COOKING_RECIPE = 7;

    /**
     * The icon path.
     *
     * @var string
     */
    const ICON_PATH = 'types';

    /**
     * @ORM\Column(type="string", length=64, unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=64, unique=true)
     *
     * @Gedmo\Slug(fields={"name"}, style="camel", separator="_")
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $emoji;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $elementName;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $color;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Genre", mappedBy="type", orphanRemoval=true)
     * @ORM\OrderBy({"slug": "ASC"})
     */
    private $genres;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Element\SpecialSet", mappedBy="type", orphanRemoval=true)
     * @ORM\OrderBy({"position": "ASC", "slug": "ASC"})
     */
    private $specialSets;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Support\Support", mappedBy="types")
     * @ORM\OrderBy({"name": "ASC"})
     */
    private $supports;

    /**
     * @ORM\Column(type="simple_array")
     */
    private $defaultLanguageSources = [];

    public function __construct()
    {
        $this->genres = new ArrayCollection();
        $this->supports = new ArrayCollection();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getEmoji(): ?string
    {
        return $this->emoji;
    }

    public function setEmoji(string $emoji): self
    {
        $this->emoji = $emoji;

        return $this;
    }

    public function getElementName(): ?string
    {
        return $this->elementName;
    }

    public function setElementName(string $elementName): self
    {
        $this->elementName = $elementName;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
            $genre->setType($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        if ($this->genres->contains($genre)) {
            $this->genres->removeElement($genre);
            // set the owning side to null (unless already changed)
            if ($genre->getType() === $this) {
                $genre->setType(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|\App\Entity\Element\SpecialSet[]
     */
    public function getSpecialSets(): Collection
    {
        return $this->specialSets;
    }

    public function addSpecialSet(SpecialSet $specialSet): self
    {
        if (!$this->specialSets->contains($specialSet)) {
            $this->specialSets[] = $specialSet;
            $specialSet->setType($this);
        }

        return $this;
    }

    public function removeSpecialSet(SpecialSet $specialSet): self
    {
        if ($this->specialSets->contains($specialSet)) {
            $this->specialSets->removeElement($specialSet);

            // set the owning side to null (unless already changed)
            if ($specialSet->getType() === $this) {
                $specialSet->setType(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Support[]
     */
    public function getSupports(): Collection
    {
        return $this->supports;
    }

    public function addSupport(Support $support): self
    {
        if (!$this->supports->contains($support)) {
            $this->supports[] = $support;
            $support->addType($this);
        }

        return $this;
    }

    public function removeSupport(Support $support): self
    {
        if ($this->supports->contains($support)) {
            $this->supports->removeElement($support);
            $support->removeType($this);
        }

        return $this;
    }

    public function getDefaultLanguageSources(): ?array
    {
        return $this->defaultLanguageSources;
    }

    public function setDefaultLanguageSources(array $defaultLanguageSources): self
    {
        $this->defaultLanguageSources = $defaultLanguageSources;

        return $this;
    }

    /**
     * Get the name.
     */
    public function __toString(): string
    {
        return (string) $this->name;
    }

    /**
     * {@inheritdoc}
     */
    public function getRouteProperties()
    {
        return [
            'type_show',
            ['type' => $this->slug],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getBreadcrumbParent()
    {
        return null;
    }

    /**
     * Get the light color.
     *
     * @throws \Lyssal\Exception\LyssalException
     *
     * @return string The color
     */
    public function getLightColor(): string
    {
        $color = new Color($this->color);
        $color->lighten(20);

        return $color->getHexadecimalColor();
    }

    /**
     * Get the dark color.
     *
     * @throws \Lyssal\Exception\LyssalException
     *
     * @return string The color
     */
    public function getDarkColor(): string
    {
        $color = new Color($this->color);
        $color->darken(60);

        return $color->getHexadecimalColor();
    }

    /**
     * Get the genres without parent.
     *
     * @return \Doctrine\Common\Collections\Collection|\App\Entity\Genre[] The genres
     */
    public function getGenreParents(): Collection
    {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->isNull('parent'))
            ->orderBy(['name' => Criteria::ASC]);

        return $this->genres->matching($criteria);
    }

    /**
     * Determine if we can add platforms with this type.
     *
     * @return bool If we can have platforms
     */
    public function canHavePlatforms(): bool
    {
        return \in_array($this->id, [self::SOFTWARE, self::VIDEO_GAME], true);
    }
}

src/Controller/StatisticController.php
<?php

/*
 * This file is part of a Lyssal project.
 *
 * @copyright Rémi Leclerc
 */

namespace App\Controller;

use App\Doctrine\Manager\Company\CompanyManager;
use App\Doctrine\Manager\Element\ElementManager;
use App\Doctrine\Manager\Person\PersonManager;
use App\Doctrine\Manager\TypeManager;
use App\Doctrine\Manager\UniverseManager;
use App\Entity\Type;
use App\Statistic\GenreStatistic;
use App\Statistic\GlobalStatistic;
use App\Statistic\OriginStatistic;
use App\Statistic\VideoGamePlatformStatistic;
use App\Statistic\WebSourceStatistic;
use App\Statistic\YearStatistic;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * The statistic controller.
 *
 * @category Controller
 *
 * @author    Rémi Leclerc
 * @copyright 2019 Rémi Leclerc
 * @license   MIT https://opensource.org/licenses/MIT
 *
 * @see https://gitlab.com/Lyssal/collectolys
 *
 * @Route("/Statistiques", name="statistic_")
 * @IsGranted("ROLE_USER")
 */
final class StatisticController extends AbstractController
{
    /**
     * The global statistics.
     *
     * @Route("/Global", name="global")
     *
     * @return \Symfony\Component\HttpFoundation\Response The view
     */
    public function global(ElementManager $elementManager, GlobalStatistic $globalStatistic): Response
    {
        return $this->render('statistic/global.html.twig', [
            'chart_config' => $globalStatistic->getConfig(),
            'global_total' => $elementManager->count(['set' => false]),
        ]);
    }

    /**
     * The universes.
     *
     * @Route("/Univers", name="universes")
     *
     * @return \Symfony\Component\HttpFoundation\Response The view
     */
    public function universes(UniverseManager $universeManager): Response
    {
        return $this->render('statistic/universes.html.twig', [
            'best_universes' => $universeManager->getRepository()->getUniverseElementCounts(48),
        ]);
    }

    /**
     * The sets.
     *
     * @Route("/Series", name="sets")
     *
     * @return \Symfony\Component\HttpFoundation\Response The view
     */
    public function sets(ElementManager $elementManager): Response
    {
        return $this->render('statistic/sets.html.twig', [
            'best_sets' => $elementManager->getRepository()->getSetElementCounts(96),
        ]);
    }

    /**
     * The video game platforms.
     *
     * @Route("/JeuxVideos/Plateformes", name="videogameplatforms")
     *
     * @return \Symfony\Component\HttpFoundation\Response The view
     */
    public function videoGamePlatforms(TypeManager $typeManager, VideoGamePlatformStatistic $videoGamePlatformStatistic): Response
    {
        return $this->render('statistic/video_game_platforms.html.twig', [
            'type' => $typeManager->findOneById(Type::VIDEO_GAME),
            'chart_config' => $videoGamePlatformStatistic->getConfig(),
            'best_platforms' => $videoGamePlatformStatistic->getBestPlatforms(),
        ]);
    }

    /**
     * The element origins.
     *
     * @Route("/Nationalites/{type}", name="origins")
     * @ParamConverter("type", options={"mapping": {"type": "slug"}})
     *
     * @return \Symfony\Component\HttpFoundation\Response The view
     */
    public function origins(OriginStatistic $originStatistic, ?Type $type = null): Response
    {
        $viewParameters = [
            'best_locations' => $originStatistic->getBestLocations($type, 16),
            'mappemonde_series' => $originStatistic->getMappemondeSeries($type),
        ];

        if (null !== $type) {
            $viewParameters['type'] = $type;
        }

        return $this->render('statistic/origins.html.twig', $viewParameters);
    }

    /**
     * The genres.
     *
     * @Route("/Genres", name="genres")
     *
     * @return \Symfony\Component\HttpFoundation\Response The view
     */
    public function genres(GenreStatistic $genreStatistic): Response
    {
        return $this->render('statistic/genres.html.twig', [
            'chart_configs' => $genreStatistic->getConfigs(),
            'best_genres_by_type' => $genreStatistic->getBestGenres(10),
        ]);
    }

    /**
     * The years.
     *
     * @Route("/Annees", name="years")
     *
     * @return \Symfony\Component\HttpFoundation\Response The view
     */
    public function years(YearStatistic $yearStatistic): Response
    {
        return $this->render('statistic/years.html.twig', [
            'chart_config' => $yearStatistic->getConfig(),
            'best_years_by_type' => $yearStatistic->getBestYears(12),
        ]);
    }

    /**
     * The companies.
     *
     * @Route("/Societes", name="companies")
     *
     * @return \Symfony\Component\HttpFoundation\Response The view
     */
    public function companies(CompanyManager $companyManager): Response
    {
        return $this->render('statistic/companies.html.twig', [
            'best_companies' => $companyManager->getRepository()->getCompanyElementCounts(48),
        ]);
    }

    /**
     * The people.
     *
     * @Route("/Personnes", name="people")
     *
     * @return \Symfony\Component\HttpFoundation\Response The view
     */
    public function people(PersonManager $personManager): Response
    {
        return $this->render('statistic/people.html.twig', [
            'best_people' => $personManager->getRepository()->getPersonElementCounts(48),
        ]);
    }

    /**
     * The web sources.
     *
     * @Route("/Sources_web", name="websources")
     *
     * @return \Symfony\Component\HttpFoundation\Response The view
     */
    public function webSources(WebSourceStatistic $webSourceStatistic): Response
    {
        return $this->render('statistic/web_sources.html.twig', [
            'chart_config' => $webSourceStatistic->getConfig(),
            'best_domains' => $webSourceStatistic->getBestDomains(),
        ]);
    }
}

templates/statistic/companies.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'companies'|trans }}
{% endblock %}

{% block breadcrumbs %}
    {{ lyssal_breadcrumb('companies'|trans, 'statistics'|trans) }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-padding-x">
        {% for  company_and_count in best_companies %}
            <div class="cell medium-6 large-4 xxlarge-2">
                <div class="callout">
                    <p>
                        <span class="lead float-right">{{ company_and_count.count|format_number }}</span>
                        <a href="{{ path('company_company_show', { company: company_and_count.slug }) }}">
                            <strong>
                                {% if company_and_count.locationEmoji is not null %}
                                    <span class="flag">{{ company_and_count.locationEmoji }}</span>
                                {% endif %}
                                {{ company_and_count.name }}
                            </strong>
                        </a>
                    </p>
                    <div class="clearfix"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/statistic/genres.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'genres'|trans }}
{% endblock %}

{% block breadcrumbs %}
    {{ lyssal_breadcrumb('genres'|trans, 'statistics'|trans) }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-padding-x">
        {% for type_id, chart_config in chart_configs %}
            <div class="cell xlarge-6">
                <div class="callout type-{{ type_id }}">
                    <h2>{{ chart_config.options.title.text }}</h2>
                    <div class="statistic-chart">
                        <canvas data-chart-config="{{ chart_config|json_encode }}"></canvas>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="grid-x grid-padding-x">
        {% for  type_and_genres in best_genres_by_type %}
            <div class="cell medium-6 large-4 xxlarge-2">
                <div class="callout type-{{ type_and_genres.type.id }}">
                    <h2>{{ appellation_html(type_and_genres.type) }}</h2>
                    <table>
                        <tbody>
                        {% for genre in type_and_genres.genres %}
                            <tr>
                                <td>
                                    <a href="{{ path('genre_show', { genre: genre.slug }) }}">
                                        {{ genre.name }}
                                    </a>
                                </td>
                                <td class="text-right">
                                    {{ genre.count }}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div class="clearfix"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/statistic/global.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'statistic.global'|trans }}
{% endblock %}

{% block breadcrumbs %}
    {{ lyssal_breadcrumb('statistic.global'|trans, 'statistics'|trans) }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-padding-x">
        <div class="cell small-12">
            <div class="callout">
                <div class="statistic-chart">
                    <canvas data-chart-config="{{ chart_config|json_encode }}"></canvas>
                </div>
                <p class="lead">
                    {{ 'total'|trans }} : {{ global_total|format_number }}
                </p>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/statistic/origins.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'origins'|trans }}
    {% if type is defined %}
        <small>{{ appellation(type) }}</small>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    {% if type is defined %}
        {{ lyssal_breadcrumb(type, '<a href="'~path('statistic_origins')~'">'~'origins'|trans~'</a>', 'statistics'|trans) }}
    {% else %}
        {{ lyssal_breadcrumb('origins'|trans, 'statistics'|trans) }}
    {% endif %}
{% endblock %}

{% block actions %}
    {% apply spaceless %}
        {% for appType in app.types %}
            <a href="{{ path('statistic_origins', { type: appType.slug }) }}" class="button type-{{ appType.id }}-background">
                <img src="{{ asset(appType.icon.url) }}" alt="{{ appType }}" title="{{ appType }}" width="16" height="16">
            </a>
        {% endfor %}
    {% endapply %}
{% endblock %}

{% block content %}
    <div class="grid-x grid-padding-x">
        <div class="cell large-9">
            <div data-preview="jvectormap-next" data-regions="{{ mappemonde_series|json_encode }}" data-color="{% if type is defined%}{{ type.darkColor }}{% else %}#333333{% endif%}" style="height: 650px;"></div>
        </div>
        <div class="cell large-3">
            <table>
                <tbody>
                {% for location in best_locations %}
                    <tr>
                        <td>
                            {% if type is defined %}
                            <a href="{{ path('element_element_listbytypeandorigin', { type: type.slug, location: location.slug }) }}">
                                {% endif %}
                                {{ location.emoji }}
                                {{ location.name }}
                                {% if type is defined %}
                            </a>
                            {% endif %}
                        </td>
                        <td class="text-right">
                            {{ location.count }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/statistic/people.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'people'|trans }}
{% endblock %}

{% block breadcrumbs %}
    {{ lyssal_breadcrumb('people'|trans, 'statistics'|trans) }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-padding-x">
        {% for  person_and_count in best_people %}
            <div class="cell medium-6 large-4 xxlarge-2">
                <div class="callout">
                    <p>
                        <span class="lead float-right">{{ person_and_count.count|format_number }}</span>
                        <a href="{{ path('person_person_show', { person: person_and_count.slug }) }}">
                            <strong>
                                {{ person_and_count.firstName }} {{ person_and_count.lastName }}
                            </strong>
                        </a>
                    </p>
                    <div class="clearfix"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/statistic/sets.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'sets'|trans }}
{% endblock %}

{% block breadcrumbs %}
    {{ lyssal_breadcrumb('sets'|trans, 'statistics'|trans) }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-padding-x">
        {% for  set_and_count in best_sets %}
            <div class="cell medium-6 large-4 xxlarge-2">
                <div class="callout type-{{ set_and_count.type_id }}">
                    <p>
                        <span class="float-right">{{ set_and_count.count|format_number }}</span>
                        <a href="{{ path('element_set_show', { set: set_and_count.id, slug: set_and_count.slug }) }}">
                            <strong>
                                {{ set_and_count.name }}
                            </strong>
                        </a>
                    </p>
                    <div class="clearfix"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/statistic/universes.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'universes'|trans }}
{% endblock %}

{% block breadcrumbs %}
    {{ lyssal_breadcrumb('universes'|trans, 'statistics'|trans) }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-padding-x">
        {% for  universe_and_count in best_universes %}
            <div class="cell medium-6 large-4 xxlarge-2">
                <div class="callout">
                    <p>
                        <span class="lead float-right" style="padding-top: 8px;">{{ universe_and_count.count|format_number }}</span>
                        <a href="{{ path('universe_show', { universe: universe_and_count.slug }) }}">
                            <strong>
                                <img src="{{ asset('images/icons/' ~ universe_and_count.icon_path ~ '/' ~ universe_and_count.icon_filename) }}" alt="{{ universe_and_count.name }}" width="48" height="48">
                                {{ universe_and_count.name }}
                            </strong>
                        </a>
                    </p>
                    <div class="clearfix"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/statistic/video_game_platforms.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'video_game.platforms'|trans }}
{% endblock %}

{% block breadcrumbs %}
    {{ lyssal_breadcrumb('video_game.platforms'|trans, 'statistics'|trans) }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-padding-x">
        <div class="cell small-12">
            <div class="callout type-{{ type.id }}">
                <div class="statistic-chart">
                    <canvas data-chart-config="{{ chart_config|json_encode }}"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="grid-x grid-padding-x">
        {% for  platform_and_count in best_platforms %}
            <div class="cell medium-6 large-4 xxlarge-2">
                <div class="callout">
                    <p>
                        <span class="lead float-right" style="padding-top: 8px;">{{ platform_and_count.count|format_number }}</span>
                        <a href="{{ path('element_element_listbytypeandplatform', { type: type.slug, platform: platform_and_count.slug }) }}">
                            <strong>
                                <img src="{{ asset('images/icons/' ~ platform_and_count.icon_path ~ '/' ~ platform_and_count.icon_filename) }}" alt="{{ platform_and_count.name }}" width="48" height="48" style="height: 48px;width: 48px;">
                                {{ platform_and_count.name }}
                            </strong>
                        </a>
                    </p>
                    <div class="clearfix"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/statistic/web_sources.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'web_sources'|trans }}
{% endblock %}

{% block breadcrumbs %}
    {{ lyssal_breadcrumb('web_sources'|trans, 'statistics'|trans) }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-padding-x">
        <div class="cell small-12">
            <div class="callout">
                <div class="statistic-chart">
                    <canvas data-chart-config="{{ chart_config|json_encode }}"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="grid-x grid-padding-x">
        {% for  domain_and_count in best_domains %}
            <div class="cell medium-6 large-4 xxlarge-2">
                <div class="callout">
                    <p>
                        <span class="lead float-right">{{ domain_and_count.count|format_number }}</span>
                        <a href="https://{{ domain_and_count.name }}" target="_blank">
                            {{ domain_and_count.name }}
                        </a>
                    </p>
                    <div class="clearfix"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/statistic/years.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'years'|trans }}
{% endblock %}

{% block breadcrumbs %}
    {{ lyssal_breadcrumb('years'|trans, 'statistics'|trans) }}
{% endblock %}

{% block content %}
    <div class="grid-x grid-padding-x">
        <div class="cell small-12">
            <div class="callout">
                <div class="statistic-chart">
                    <canvas data-chart-config="{{ chart_config|json_encode }}"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="grid-x grid-padding-x">
        {% for  type_and_years in best_years_by_type %}
            <div class="cell medium-6 large-4 xxlarge-2">
                <div class="callout type-{{ type_and_years.type.id }}">
                    <h2>{{ appellation_html(type_and_years.type) }}</h2>
                    <table>
                        <tbody>
                            {% for year in type_and_years.years %}
                                <tr>
                                    <td>
                                        <a href="{{ path('element_element_listbytypeandyear', { type: type_and_years.type.slug, year: year.year }) }}">
                                            {{ year.year }}
                                        </a>
                                    </td>
                                    <td class="text-right">
                                        {{ year.count }}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="clearfix"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}